### ISSUE TITLE
Internal debugger error: <nil> not an Int

### ISSUE THREAD

**Issue by erifan** [go-delve/delve#3133]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.9.1
Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $

3. What version of Go are you using? (`go version`)?
go version devel go1.20-41089704dd Fri Sep 9 01:59:25 2022 +0000 linux/arm64

5. What operating system and processor architecture are you using?
linux/arm64
macos/m1

7. What did you do?
$ dlv exec go-master/pkg/tool/linux_arm64/compile -- foo.go
(dlv) b ssa.(*regAllocState).regalloc
(dlv) c

And foo.go is as follow:
```
package foo
var ll int = 1000
func foo() {
        const N = 64
        a := make([]uint64, N)
        for i := 0; i < ll; i++ {
                for j := range a {
                        a[j] ^= 1 << 37
                }
        }
}
```

9. What did you expect to see?
No failure

11. What did you see instead?
Command failed: Internal debugger error: <nil> not an Int
runtime.gopanic (0x102cdaf5b)
        /usr/local/go/src/runtime/panic.go:965
go/constant.Int64Val (0x102e95027)
        /usr/local/go/src/go/constant/value.go:476
github.com/go-delve/delve/pkg/proc.(*Variable).parseG.func2 (0x102fa9b1b)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/pkg/proc/variables.go:879
github.com/go-delve/delve/pkg/proc.(*Variable).parseG (0x102f9c987)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/pkg/proc/variables.go:901
github.com/go-delve/delve/pkg/proc.GetG (0x102f9955b)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/pkg/proc/variables.go:258
github.com/go-delve/delve/pkg/proc.(*BreakpointState).checkCond (0x102f68cc7)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/pkg/proc/breakpoints.go:278
github.com/go-delve/delve/pkg/proc.(*Breakpoint).checkCondition (0x102f68977)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/pkg/proc/breakpoints.go:258
github.com/go-delve/delve/pkg/proc.(*Target).Continue (0x102f90c03)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/pkg/proc/target_exec.go:84
github.com/go-delve/delve/service/debugger.(*Debugger).Command (0x10300051f)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/service/debugger/debugger.go:1162
github.com/go-delve/delve/service/rpc2.(*RPCServer).Command (0x10304e017)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/service/rpc2/server.go:129
reflect.Value.call (0x102d66f3f)
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call (0x102d666f3)
        /usr/local/go/src/reflect/value.go:337
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func3 (0x10311e14f)
        /usr/local/gopath/pkg/mod/github.com/go-delve/delve@v1.7.3/service/rpccommon/server.go:372
runtime.goexit (0x102d0f203)
        /usr/local/go/src/runtime/asm_arm64.s:1130

**Comment by aarzilli** [comment]
This is because of #3129

**Comment by aarzilli** [comment]
Closing because #3129 was fixed.

**Comment by GitHubUserC** [comment]
This issue has not been fixed, #3129 did not solve my problem.

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
```
3. What version of Go are you using? (`go version`)?
`go version go1.20.3 linux/amd64`
5. What operating system and processor architecture are you using?
```
Description:    Ubuntu 22.04.2 LTS
Architecture:            x86_64
```
7. What did you do?
```
package main

import (
	"fmt"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr"
)

func main() {
	var x, y, z, z8 [8]fr.Element
	for i := 0; i < 8; i++ {
		x[i].SetRandom()
		y[i].SetRandom()

		z[i].Mul(&x[i], &y[i])
	}

	fmt.Printf("%#X %#X %#X %#X\n", x[0][0], x[0][1], x[0][2], x[0][3])
	fmt.Printf("%#X %#X %#X %#X\n", z[0][0], z[0][1], z[0][2], z[0][3])
}
```
9. What did you expect to see?

I import [a third-party library](github.com/consensys/gnark-crypto/ecc/bn254/fr) that uses Golang assembly, and I want to debug the assembly code, for example to see the values of registers at some steps, but when I use it, an error occurs as next.

11. What did you see instead?
```
$ dlv debug main.go --check-go-version=false
Type 'help' for list of commands.
(dlv) b main.go:14
Breakpoint 1 set at 0x4c9e5e for main.main() ./main.go:14
(dlv) c
Command failed: Internal debugger error: <nil> not an Int
runtime.gopanic (0x4365b2)
        /usr/local/go/src/runtime/panic.go:884
go/constant.Int64Val (0x620c05)
        /usr/local/go/src/go/constant/value.go:516
github.com/go-delve/delve/pkg/proc.(*Variable).parseG.func1 (0x6f7428)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/variables.go:822
github.com/go-delve/delve/pkg/proc.(*Variable).parseG (0x6f6f81)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/variables.go:846
github.com/go-delve/delve/pkg/proc.GetG (0x6f3e8d)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/variables.go:247
github.com/go-delve/delve/pkg/proc/native.(*nativeThread).SetCurrentBreakpoint (0x74ca39)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/native/threads.go:131
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).stop (0x74aa92)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/native/proc_linux.go:527
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).ContinueOnce (0x747297)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/native/proc.go:271
github.com/go-delve/delve/pkg/proc.(*Target).Continue (0x6ea2cf)
        /home/asus/go/src/github.com/derekparker/delve/pkg/proc/target_exec.go:70
github.com/go-delve/delve/service/debugger.(*Debugger).Command (0x754658)
        /home/asus/go/src/github.com/derekparker/delve/service/debugger/debugger.go:856
github.com/go-delve/delve/service/rpc2.(*RPCServer).Command (0x7e00d6)
        /home/asus/go/src/github.com/derekparker/delve/service/rpc2/server.go:124
reflect.Value.call (0x4d0cca)
        /usr/local/go/src/reflect/value.go:586
reflect.Value.Call (0x4cff7b)
        /usr/local/go/src/reflect/value.go:370
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func3 (0x889cb9)
        /home/asus/go/src/github.com/derekparker/delve/service/rpccommon/server.go:338
runtime.goexit (0x468ee0)
        /usr/local/go/src/runtime/asm_amd64.s:1598
```
